services:
  - type: web
    name: finkid-be
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
